name: Run tests

on:
  push:
  pull_request:
  release:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        node: [ '10', '12', '14', '15' ]
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
    runs-on: ${{ matrix.os }}
    name: Node v.${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test
